export const ServiceList_lang = {
    EN : [
        {
            title: 'Email Aliases',
            id: 1,
            haveService: true,
            nextPaymentOn: 'Next payment on',
            hasServiceText: '{date}',
            noServiceText: 'Create unlimited aliases for your email',
            cName: 'dropdown-link',
            buttonLearnMore: 'Learn more',
            buttonViewDetails: 'View details',
            imagePath: 'images/anti-spam-protection.png',
            imageTitle: 'emails',
            detailPath: '/EmailDashboard',
            buttonLearnMorePath: '/EmailRedirector',
            planName: 'Gold'
        },
        {
            title: 'Virtual Credit Card',
            id: 2,
            haveService: false,
            nextPaymentOn: 'Next payment on',
            hasServiceText: '{date}',
            noServiceText: 'Create virtual credit card to protect your true credit card informations',
            cName: 'dropdown-link',
            buttonLearnMore: 'Learn more',
            buttonViewDetails: 'View details',
            imagePath: 'images/online-sopping.png',
            imageTitle: 'vcc',
            detailPath: '/VCCDashboard',
            buttonLearnMorePath: '/vcc',
            planName: 'Diamond'
        },
        {
            title: 'Payment - Subscribe to a service',
            id: 3,
            haveService: true,
            nextPaymentOn: 'Select services and manage payment methods',
            hasServiceText: '',
            noServiceText: 'Select services and manage payment methods',
            cName: 'dropdown-link',
            buttonLearnMore: 'Learn more',
            buttonViewDetails: 'View details',
            imagePath: 'images/person.png',
            imageTitle: 'payments',
            detailPath: '/payments',
            buttonLearnMorePath: '/payments',
            planName: 'free'
        }],

        FR:[
            {
                title: 'Alias de courriel',
                id: 1,
                haveService: true,
                hasServiceText: '{date}',
                noServiceText: "Creez un nombre illimite d'alias pour votre courriel",
                cName: 'dropdown-link',
                buttonLearnMore: 'En apprendre plus',
                buttonViewDetails: 'Voir les details',
                imagePath: 'images/svg-2.svg',
                imageTitle: 'emails',
                detailPath: '/EmailDashboard',
                buttonLearnMorePath: '/EmailRedirector',
                planName: 'OR'
            },
            {
                title: 'Carte de credit virtuelle',
                id: 2,
                haveService: false,
                hasServiceText: '{date}',
                noServiceText: 'Creez des cartes de credit virtuelle afin de proteger vos informations de paiement',
                cName: 'dropdown-link',
                buttonLearnMore: 'En apprendre plus',
                buttonViewDetails: 'Voir les details',
                imagePath: 'images/svg-1.svg',
                imageTitle: 'vcc',
                detailPath: '/VCCDashboard',
                buttonLearnMorePath: '/vcc',
                planName: 'Diamand'
            },
            {
                title: 'Paiement - Souscrire a un service',
                id: 3,
                haveService: false,
                hasServiceText: '{date}',
                noServiceText: 'Selectionnez des services et gerer vos methodes de paiement',
                cName: 'dropdown-link',
                buttonLearnMore: 'En appprendre plus',
                buttonViewDetails: 'View details',
                imagePath: 'images/svg-3.svg',
                imageTitle: 'payments',
                detailPath: '/payments',
                buttonLearnMorePath: '/payments',
                planName: 'Gratuit'
            },
        ]
}